### ISSUE TITLE
NEMU Incorrectly Raises Illegal Instruction Exception on csrw fcsr, s1 When mstatus.FS ≠ 0

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#583]
**Describe the bug**

 I encountered a problem when testing xiangshan with the **nemu** simulator. NEMU raised an `illegal instruction exception` when executing the instruction `csrw fcsr, s1`. This behavior is unexpected because the `FS` field in the mstatus register is set to `11 (Dirty)`, which should allow access to floating point CSRs such as fcsr. xiangshan handles the instruction correctly without raising an exception.

**To Reproduce**

Run the following command to execute the test image with NEMU as the reference model:

`./build/emu -b 0 -e 0 -i id_3098.img --diff /xs-env/XiangShan/ready-to-run/riscv64-nemu-interpreter-so`

![image](https://github.com/user-attachments/assets/d51575d1-ce01-4d54-8c5f-5ee37955121e)
![image](https://github.com/user-attachments/assets/2939e137-7a1d-40f0-b387-d4ae6b14a857)
![image](https://github.com/user-attachments/assets/25a83069-13c7-4db7-902a-192e434b3f05)

The above inconsistency also occurs when executing the command `./build/emu -b 0 -e 0 -i id_3098.img --diff /xs-env/XiangShan/ready-to-run/riscv64-spike-so`

**Expected behavior**

When I use spike in https://github.com/riscv-software-src/riscv-isa-sim for debugging, the behavior is consistent with xiangshan.

`spike -d --pc=0x80000000 id_3098.elf`

![image](https://github.com/user-attachments/assets/a1686559-4e6b-4ca9-9d64-d91b8ed65a48)

**Necessary information on versions**
**Xiangshan**:commit ea2894c8c273b00083141d9258b412ed910b28f9 (HEAD, origin/master, origin/HEAD)

**Ready-to-run**:
commit 2ade2e3879e019f6400cb33efbb62513166d139b (HEAD, origin/master, origin/HEAD)
Author: linzhida <linzhida19@mails.ucas.ac.cn>
Date:   Sat Oct 12 18:38:24 2024 +0800

    Bump nemu ref in ready-to-run
    
        * NEMU commit: 300b282c158dbd2d4bd23edf4f682b27a0d711be
        * NEMU configs:
            * riscv64-xs-ref_defconfig
            * riscv64-dual-xs-ref_defconfig
    
        Including:
            * fix(paddr): raise SAF if type is MEM_TYPE_WRITE (#576)
            * fix(csr): fix csr read/write logic.
**Additional information**

This is the test program[id_3098.zip](https://github.com/user-attachments/files/17358982/id_3098.zip)

**Comment by NewPaulWalker** [comment]
This is not a bug in NEMU, but an issue with your test program.

The problem is that NEMU executes the instruction at PC 0x80036344, but the instruction encoding is 0x13349073. This causes NEMU to attempt to access the nonexistent CSR at 0x133 instead of the FCSR at 0x3, resulting in an illegal instruction exception. 

This occurred because your program modified itself before executing that instruction. 

Specifically, after executing a jump instruction at PC 0x8004380c, a `sw` instruction was executed. 

![1729767074330](https://github.com/user-attachments/assets/545453bb-db5f-4479-b485-ba40a92fba15)

According to the disassembly obtained from the ELF file you provided, there is no instruction at PC 0x800362e6; only the instructions at 0x800362e4 and 0x800362e8 exist. 

![1729767143602](https://github.com/user-attachments/assets/447dfc3f-53d4-4db2-9612-8d0c6e44f678)

This means that the previous jump instruction led to an unexpected location, executing the instruction `c.sw s0, 96(a2)`. 

Here, the value of `s0` is 0xffff4f13020f1f13, with the least significant byte being 0x13. The value in `a2` is 0x800362e7, and adding the offset of 96 results in a memory address of 0x80036347, leading to writing a 0x13 byte to address 0x80036347. Consequently, when executing the instruction at 0x80036344, the fetched instruction is 0x13349073 instead of 0x00349073.
