### ISSUE TITLE
Handling Error When Executing Specific “Unknown” Instructions

### ISSUE THREAD

**Issue by vincen-dev** [OpenXiangShan/NEMU#636]
**Describe the bug**

Refer to the issue I submitted before: https://github.com/OpenXiangShan/NEMU/issues/597 . I re-used some **illegal instructions** to test. The following two situations occurred:

**1. Wrong handling of value in `mtval` register in nemu.**

The main assembly code is as follows:

```
    .word 0x0001061f    #unknown
    xor t0,t0,t0
    .word 0x4a3e88eb    #unknown
```
![image](https://github.com/user-attachments/assets/7fc0646f-720c-41ed-b557-97334dd5bbeb)
![image](https://github.com/user-attachments/assets/0732c92f-e098-49b0-86fd-edb6cbdb27f0)

From the screenshot above, we can see that the behavior of nemu and xiangshan differs when they execute the .word 0x4a3e88eb instruction. The `mtval` register of xiangshan stores the machine code of the current instruction, but the `mtval` register of nemu stores the machine code of the previous unknown instruction (`0x1061f`).

This is my test program ：[mtval.zip](https://github.com/user-attachments/files/17633345/mtval.zip)

**2. The values ​​of nemu and xiangshan mcause registers are different**

The main assembly code is as follows:

```
    .word 0x4a3e88eb    #unknown
    xor t0,t0,t0
    .word 0x0001061f    #unknown
```
![image](https://github.com/user-attachments/assets/a527d77f-3e05-486a-b4a9-f47a42f009cf)
![image](https://github.com/user-attachments/assets/f023b3df-1711-43f7-b495-353ba368d857)

From the screenshot above, we can see that an exception occurred in xiangshan, but no exception occurred in nemu.Other similar unknown instructions include `.word 0x53d48a6b` and `.word 0x6001`, etc.

This is my test program ：[mcause.zip](https://github.com/user-attachments/files/17633440/mcause.zip)

**Necessary information on versions**
    * NEMU commit: 861f8d3187fa8a58e14d2394d56b28f1f434adc2
    * NEMU configs:
      * riscv64-xs-ref_defconfig
      * riscv64-dual-xs-ref_defconfig

**Comment by NewPaulWalker** [comment]
Thank you for your issue.
This is the same problem as this [issue](https://github.com/OpenXiangShan/NEMU/issues/637), both of which are due to the inconsistency in the definition of simulation termination instructions between XiangShan and NEMU.

For the instruction 0x53d48a6b in the two tests you provided, XiangShan considers it an illegal instruction, while NEMU considers it a simulation termination instruction, leading to inconsistent behavior.

In addition, in the second test, there is also a mcause inconsistency, while the first test does not show this inconsistency.
The reason is that in the first test, after encountering 0x6001 and reporting an illegal instruction with mcause set to 2, I believe that you did not reset mcause during exception handling.
Therefore, when the next instruction 0x53d48a6b is encountered, even though NEMU does not recognize it as an illegal instruction, the value of mcause remains 2.
As a result, there is no visible mcause inconsistency in the first test.
