### ISSUE TITLE
When the fs field in the mstatus register is 0, there is a difference in executing instructions such as flh

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#641]
**Describe the bug**

When I was testing Xiangshan, executing the following assembly instructions showed differences between nemu, xiangshan and spike
```
.section .text
.globl _start
_start:
    li     t0, 0x8000000a00100a00     #FS: 00
    csrw    mstatus, t0 
    flh     ft0, 9(sp) 
```

**To Reproduce**

When using nemu as a reference model：
![image](https://github.com/user-attachments/assets/23d2a470-db62-4ad9-942e-b3b9f2de8417)
![image](https://github.com/user-attachments/assets/23f9ecd1-4c8d-4468-a128-bc98b025dd92)

When using riscv64-spike-so as a reference model:
![image](https://github.com/user-attachments/assets/0734f6e3-20d9-4eaf-b54e-6f69b36caa03)
![image](https://github.com/user-attachments/assets/7c0769c8-7978-491e-a362-2a2a1b95b8ff)

**Expected behavior**
FS is 0, xiangshan should also trigger an illegal instruction exception. After testing, there are also such instructions as `fsh`, etc.

**Necessary information on versions**
xiangshan:commit 7af39ad2ddb1305b2c4ddf4c3a9663a7c3615fa6 (HEAD -> master, origin/master, origin/HEAD)
 NEMU commit: 861f8d3187fa8a58e14d2394d56b28f1f434adc2
ready-to-run:commit c09f524c6ecb43cd047b226e2da4aad7edd05702 (HEAD, origin/master, origin/HEAD)

**Comment by NewPaulWalker** [comment]
This should be a bug in XiangShan, and you should ask about it in the XiangShan repository.

As for the mstatus inconsistency when using Spike as the reference model, this is because both XiangShan and NEMU have implemented the SMDBLTRP extension (RISC-V M-mode Double Trap Extension), which is not implemented in Spike.
If you would like to learn more about this, you should refer to the RISC-V manual.
