### ISSUE TITLE
`mcause` error  in NEMU

### ISSUE THREAD

**Issue by ha0lyu** [OpenXiangShan/NEMU#652]
This is a same bug as #629, but the PR #628 did not fix it completely. The right value should be 7.

```
sw s1, 60(a1)
```
![image](https://github.com/user-attachments/assets/be26b277-c9cc-4dbf-92e7-eec92636f5a6)

![image](https://github.com/user-attachments/assets/576dc1ce-8f35-46c6-9b05-7ad80022e780)

**env:**
XiangShan branch: master
XiangShan commit id: https://github.com/OpenXiangShan/XiangShan/commit/4376b52554432c985f5eeba9c9d0df8033078f42
NEMU commit id: a4815f99

**Comment by NewPaulWalker** [comment]
@ha0lyu Thank you for your issue.
As mentioned by @fly-1011 , this is a new bug introduced by commit a4815f9981d5c4c5ed59f09e98024701bb188f1b.
I believe it was caused by a copy-paste error when @Anzooooo  added this feature.
I have already fixed the issue in https://github.com/OpenXiangShan/NEMU/pull/657.
