### ISSUE TITLE
[Bug report] debug register `tinfo` is read-only.

### ISSUE THREAD

**Issue by ha0lyu** [OpenXiangShan/NEMU#663]
When we access `tinfo` register, NEMU will return some different value,
According to the [debug manual](https://riscv.org/wp-content/uploads/2019/03/riscv-debug-release.pdf), `tinfo` is **read-only.**
<img width="436" alt="image" src="https://github.com/user-attachments/assets/c240b828-f04e-43b4-9012-ec19844a53ef">

**But if we write it, it changed in NEMU:**
<img width="840" alt="image" src="https://github.com/user-attachments/assets/3595d1d0-4a0e-4cd5-828a-c9164ed8b90e">
_Before write tinfo, it's value is 0x40, same as XiangShan._

<img width="760" alt="image" src="https://github.com/user-attachments/assets/529f5ee5-96d0-4f1d-8f84-85359644affc">

**Test case**:
```
    csrr t0, tinfo
    csrrwi  s3, tinfo, 17
```

**Version**:
    XiangShan: master, 011f1effd
    NEMU: b9507fbc

**Comment by NewPaulWalker** [comment]
Thank you for your issue.
First, please update your debug manual version. In the new manual, `tinfo` is a read/write register, and writing to this read/write CSR has no effect. This is different because writing to a read-only CSR should raise an illegal instruction exception.
![image](https://github.com/user-attachments/assets/7bfed98e-1998-47fc-bcb6-89c176ac5956)

Secondly, this is indeed a bug in NEMU. When writing to tinfo, NEMU should retain the old value. I have already fixed this via a PR.

**Comment by ha0lyu** [comment]
> please update your debug manual version.

Thanks for the reminder. I didn’t notice the new version before. I found it now. Thanks again.
